# Database configuration
database:
  type: "sqlite"
  host: "localhost"
  port: 3306
  username: "root"
  password: "example"
  database: "kingdoms"
  ssl: false

# Messages configuration
messages:
  commands:
    player-only: "&8» &cOnly players can use this command"
    no-permission: "&8» &cYou don't have permission to use this command"
    player-not-found: "&8» &cThe player is not online"
    create-kingdom:
      usage: "&8» &cUsage: /kingdom create <name>"
      already-have-kingdom: "&8» &cYou already have a kingdom"
      success: "&8» &aYou have created the kingdom &e%name%"
      error: "&8» &cAn error occurred while creating the kingdom"
      territory-already-claimed: "&8» &cYou can't create a kingdom here, the territory is already claimed"
    list-kingdoms:
      no-kingdoms: "&8» &cThere are no kingdoms"
      success: |
        &8» &aKingdoms:
        &8» &7Name: &e%name%
    delete-kingdom:
      not-found: "&8» &cThe kingdom was not found"
      success: "&8» &aYou have deleted the kingdom &e%name%"
      error: "&8» &cAn error occurred while deleting the kingdom"
  guis:
    kingdom-not-found: "&8» &cThe kingdom was not found"
  conversations:
    rename-kingdom:
      prompt: "&8» &7What name do you want to give to your kingdom?"
      success: "&8» &aYou have renamed the kingdom to &e%name%"