# Database configuration
database:
  type: "sqlite"
  host: "localhost"
  port: 3306
  username: "root"
  password: "example"
  database: "kingdoms"
  ssl: false

# Kingdom configuration
kingdom:
  war-time: 10
  war-experience: 100
  levels:
    1:
      experience: 100
      max-members: 10
      max-territories: 3
    2:
      experience: 250
      max-members: 20
      max-territories: 5
    3:
      experience: 500
      max-members: 30
      max-territories: 8
    4:
      experience: 1000
      max-members: 50
      max-territories: 12
    5:
      experience: 2000
      max-members: 70
      max-territories: 20

# Messages configuration
messages:
  commands:
    player-only: "&8» &cOnly players can use this command"
    no-permission: "&8» &cYou don't have permission to use this command"
    player-not-found: "&8» &cThe player is not online"
    create-kingdom:
      usage: "&8» &cUsage: /kingdom create <name>"
      already-have-kingdom: "&8» &cYou already have a kingdom"
      success: "&8» &aYou have created the kingdom &e%name%"
      error: "&8» &cAn error occurred while creating the kingdom"
      territory-already-claimed: "&8» &cYou can't create a kingdom here, the territory is already claimed"
    delete-kingdom:
      not-found: "&8» &cThe kingdom was not found"
      success: "&8» &aYou have deleted the kingdom &e%name%"
      error: "&8» &cAn error occurred while deleting the kingdom"
    claim-territory:
      already-claimed: "&8» &cThe territory is already claimed"
      success: "&8» &aYou have claimed the territory"
      max-territories: "&8» &cYou have reached the maximum number of territories"
    unclaim-territory:
      not-claimed: "&8» &cThe territory is not claimed"
      no-kingdom: "&8» &cYou don't have a kingdom"
      not-your-territory: "&8» &cYou can't unclaim this territory"
      last-territory: "&8» &cYou can't unclaim the last territory"
      success: "&8» &aYou have unclaimed the territory"
    member-kingdom:
      usage: "&8» &cUsage: /kingdom member <player>"
      no-kingdom: "&8» &cYou don't have a kingdom"
      success: "&8» &aYou have added &e%player% &ato the kingdom"
      max-members: "&8» &cYou have reached the maximum number of members"
  guis:
    kingdom-not-found: "&8» &cThe kingdom was not found"
    no-kingdoms: "&8» &cThere are no kingdoms"
    next-page: "&8» &aNext page"
    previous-page: "&8» &aPrevious page"
    cant_war_yourself: "&8» &cYou can't declare war to your own kingdom"
    remove-member:
        success: "&8» &aYou have removed &e%player% &afrom the kingdom"
        error: "&8» &cAn error occurred while removing the player from the kingdom"
  conversations:
    rename-kingdom:
      prompt: "&8» &7What name do you want to give to your kingdom?"
      success: "&8» &aYou have renamed the kingdom to &e%name%"
    war-confirm:
      prompt: "&8» &7Do you want to declare war to the kingdom &e%name%&7? (yes/no)"
      success: "&8» &aYou have declared war to the kingdom &e%name%"
      no-war: "&8» &cYou have decided not to declare war"
      invalid: "&8» &cInvalid response"
    war-accept:
      prompt: "&8» &7Do you want to accept the war declared by the kingdom &e%name%&7? (yes/no)"
      success: "&8» &aYou have accepted the war declared by the kingdom &e%name%"
      title-success: "&a&lWar accepted"
      subtitle-success: "&7You have accepted the war declared by the kingdom &e%name%"
      subtitle-success-attacker: "&7The kingdom &e%name% &7has accepted the war"
      no-war: "&8» &cYou have decided not to accept the war"
      no-war-attacker: "&8» &cThe kingdom &e%name% &cdecided not to accept the war"
      invalid: "&8» &cInvalid response"
  listeners:
    title: "&a&l%name%"
    subtitle: "&7You have entered the territory of &e%name%"
  managers:
    bossbar:
      name: "&a&lWar"
    level-up:
      title: "&a&lLevel up"
      subtitle: "&7You have reached level &e%level%"
    war:
      title-success: "&a&lWar declared"
      subtitle-success: "&7You won the war against the kingdom &e%name%"
      title-failure: "&c&lWar declared"
      subtitle-failure: "&7You lost the war against the kingdom &e%name%"